name: laughter-analysis
dependencies:
  - python=3.4
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - pip:
    - plotly==2.5.1
    - dash==0.21.0
    - dash_core_components==0.22.1
    - dash_html_components==0.10.0
    - pyaudio==0.2.11
    - resampy==0.2.0
    - h5py==2.7.1
    - dash-renderer==0.12.1
    - phue==1.0
    - keras==2.0.6
    - tensorflow==1.14.0
    - six==1.11.0
    - scipy==0.19.1
    - partd
    - bokeh
    - ipykernel
